name: auto-merge	
on:	
  pull_request:	
    types:	
      - labeled	
      - unlabeled	
      - synchronize	
      - opened	
      - edited	
      - ready_for_review	
      - reopened	
      - unlocked	
  pull_request_review:	
    types:	
      - approved	
jobs:	
  automerge:	
    runs-on: ubuntu-latest	
    steps:	
      - name: auto-merge	
        uses: "pascalgn/automerge-action@v0.11.0"	
        env:	
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
          AUTOMERGE: ""
          MERGE_RETRIES: "12"
